services:
  contendor_mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_USER: daniel
      MYSQL_PASSWORD: dsecret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - mi_red
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
    command: >
      --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mi_phpmyadmin
    environment:
      PMA_HOST: contendor_mysql  # Nombre del servicio de MySQL
    ports:
      - "8081:80"
    networks:
      - mi_red

  apache-php:
    build:
      context: ./Dockerfile  # Ajusta según la ruta donde esté tu Dockerfile
      dockerfile: apache_file  # Asegúrate de que el nombre del Dockerfile coincida
    container_name: apache-container
    volumes:
      - ./www/:/var/www/html
    expose:
      - 80
    ports:
      - 80:80
    links:
      - contendor_mysql
    networks:
      - mi_red

networks:
  mi_red:
    driver: bridge
